# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "master"

pool:
  vmImage: 'windows-2019'
variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip
steps:
- checkout: self  # self represents the repo where the initial Azure Pipelines YAML file was found
  clean: true
  submodules: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: Set Python Version to 3.8
- task: PowerShell@2
  displayName: 'start mssqllocaldb'
  inputs:
    targetType: 'inline'
    script: 'sqllocaldb start mssqllocaldb'
- script: |
    mkdir $(venv)
    python -m venv venv
  displayName: Create Virtual Environment
- task: Cache@2
  inputs:
    key: pip | dev_requirements.txt | requirements.txt
    path: $(PIP_CACHE_DIR)
  displayName: Cache requirements
- script: |
    call venv\Scripts\activate.bat
    python -m pip install -r requirements.txt
    python -m pip install -r dev_requirements.txt
  displayName: Install requirements
- script: |
    set PATH=%PATH%;$(System.DefaultWorkingDirectory)\venv\Scripts
    echo %PATH%
    pre-commit run --all-files
  displayName: run pre-commit
- script: |
    call venv\Scripts\activate.bat
    python -m pip install -r dev_requirements.txt
  displayName: Install Development Requirements
- script: |
    call venv\Scripts\activate.bat
    set PIPELINE=1
    set PYTHONPATH=%PYTHONPATH%;$(System.DefaultWorkingDirectory);$(System.DefaultWorkingDirectory)\tsl
    python dev_scripts/setup_test_db.py
  displayName: Setup test database on local server
- script: |
    call venv\Scripts\activate.bat
    set PYTHONPATH=%PYTHONPATH%;$(System.DefaultWorkingDirectory);$(System.DefaultWorkingDirectory)\tsl
    set PIPELINE=1
    set EDOC_ENV=DEV
    set PSE_ENV=DEV
    python -m pip install pytest-azurepipelines pytest-cov
    pytest --log-cli-level DEBUG --log-date-format="%Y-%m-%d %H:%M:%S" --junitxml=result.xml -vv tests/ --cov=tsl --cov-report html
  displayName: Run pytest test cases
