name: type_check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlabeled]
    branches:
      - master

jobs:
  type_check:
    name: check code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: pip install poetry

    - name: Install project dependencies
      run: poetry install --no-root

    - name: Analysing the code with mypy
      run: poetry run mypy --config-file dev_config/mypy.ini qute_style qute_style_examples dev_scripts tests --exclude resources_cl.py
